config/routes.rb
post '/roles/:from/do_copy_to', :to => 'roles#do_copy_members'
post '/roles/:from/validate_copy_members', :to => 'roles#validate_copy_members'

app/views/roles/_copy_members.html.erb
<%
#
#    Copyright (C) 2014 Savoir-faire Linux Inc. (<www.savoirfairelinux.com>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
%>
<br/><br/>
<h3><%= raw l(:copy_members_to_another_role) %></h3>

<%= form_tag({:action => 'validate_copy_members', from: @role.id}, :method => 'post') do %>

    <div class="box tabular">

        <p>
            <label for="copy_role_id"><%= raw l(:target_role_where_to_copy_members) %><span class="required"> *</span></label>
            <%= collection_select(:copy, :role_id, Role.where('id <> ?', @role.id), :id, :name) %>
        </p>

        <p>
            <label for="copy_remove_from_source"><%= raw l(:move_instead_of_copy) %><span class="required"> *</span></label>
            <%= check_box("copy", "remove_from_source") %>
        </p>

    </div>

    <%= submit_tag l(:next_step) %>

<% end %>

app/views/roles/edit.html.erb
<%= render :parent %>

<%= render 'copy_members' %>

app/views/roles/validate_copy_members.html.erb
<%
#
#    Copyright (C) 2014 Savoir-faire Linux Inc. (<www.savoirfairelinux.com>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
%>
<%= title [l(:label_role_plural), roles_path], @role.name, l(@remove_from_source ? :label_move_to : :label_copy_to), @target_role.name %>
<hr/>

<% if @overview.count > 0 %>

<% @overview.each do |project, members| %>

<div class="autoscroll confirmation-role-copy">
    <%
    # quick fix, sorry
    count = 0
    dones = []
    members.each do |member_role|
        next if member_role.member.user.nil? or dones.include? member_role.member.id
        dones << member_role.member.id
        count += 1
    end
    %>
    <h2><%= project.name %> (<%= l(:migrating)+' '+(count.to_s)+' '+l(:members, :count => count) %>)</h2>
    <table class="list">
        <thead>
            <tr>
                <th><%= l(:field_user) %></th>
                <th class="roles"><%= l(:roles_before) %></th>
                <th class="roles"><%= l(:roles_after) %></th>
            </tr>
        </thead>
        <tbody>
            <%
            i = 0
            dones = []
            %>
            <% members.each do |member_role| next if member_role.member.user.nil? or dones.include? member_role.member.id %>
            <tr class="<%= i % 2 == 0 ? 'odd' : 'even' %> project root parent ">
                <%
                dones << member_role.member.id
                selection = member_role.member.roles.pluck(:name).sort_by(&:downcase)
                %>
                <td class="name"><%= member_role.member.user.name %></td>
                <td class="roles">
                    <% if @remove_from_source %>
                        <%= sanitize(selection.uniq.map{|x| x == @role.name ? '<span class="rm">'+x+'</span>' : x}.join(', '), tags: %w(span), attributes: %w(class)) %>
                    <% else %>
                        <%= selection.uniq.join(', ') %>
                    <% end %>
                </td>
                <td class="roles">
                    <% if @remove_from_source %>
                        <%= sanitize((selection.push(@target_role.name) - [@role.name]).uniq.map{|x| x == @target_role.name ? '<span class="add">'+x+'</span>' : x}.join(', '), tags: %w(span), attributes: %w(class)) %>
                    <% else %>
                        <%= sanitize(selection.push(@target_role.name).uniq.map{|x| x == @target_role.name ? '<span class="add">'+x+'</span>' : x}.join(', '), tags: %w(span), attributes: %w(class)) %>
                    <% end %>
                </td>
            </tr>
            <% i += 1 %>
            <% end %>
        </tbody>
    </table>
</div>
<br/>
<% end %>

<div class="box tabular" id="members_copy">
    <%= form_tag({:action => 'do_copy_members', from: @role.id}, :method => 'post') do %>
    <input type="hidden" name="copy[role_id]" value="<%= @target_role.id %>" />
    <input type="hidden" name="copy[remove_from_source]" value="<%= request.POST['copy']['remove_from_source'] %>" />
    <p>
        <i><%= l(:this_option_is_irreversible) %></i>
    </p>
    <p>
        <label for="copy_legitimate"><%= raw l(:check_this_box_to_validate) %><span class="required"> *</span></label>
        <%= check_box("copy", "legitimate") %>
    </p>
    <%= submit_tag l(@remove_from_source ? :launch_move : :launch_copy) %>
    <% end %>
</div>

<style>
.confirmation-role-copy td.name {
    width: 22%;
}
.confirmation-role-copy th, .confirmation-role-copy td {
    text-align:left!important;
}
.confirmation-role-copy .roles {
    width: 39%;
}
.confirmation-role-copy .rm {
    background-color:lightpink;
    color:black;
}
.confirmation-role-copy .add {
    background-color:lightgreen;
    color:black;
}
#members_copy label {
    width:auto!important;
    margin-right: 9px;
}
</style>
<% else %>
    <p><%= l(:no_members_to_migrate) %></p>
<% end %>